### PR TITLE
v1.8: Fix verify in advised beans

### PR DESCRIPTION
**Pull request by antoinemeyer**
fixes https://github.com/antoinemeyer/mock-in-bean/issues/23

I am not entirely happy with that solution, but it does work (until it will not).
Tested on `2.6.15`, `2.7.18`, `3.0.13`, `3.1.12`, `3.2.11`, `3.3.5`.

### CODE REVIEW

**Comment by inkassso** [comment]
While this change does fix the root cause, I don't think the solution is correct.

From what I understand, the only difference now is unwrapping the proxy and injecting the spy with the actual service instance directly into target bean. However, that removes the proxy and with it also any intercepting actions, e.g. Transaction handling, Async execution or similar. I believe that should be kept, i.e. when the spied bean is a proxy, don't overwrite the proxy in the target bean, but instead just overwrite the target in the proxy. See [WorkingLoggingServiceTest4_ManualInjectionWithinProxy.java](https://github.com/inkassso/mock-in-bean-issue-23/blob/master/src/test/java/com/github/inkassso/mockinbean/issue23/service/WorkingLoggingServiceTest4_ManualInjectionWithinProxy.java), where I got this working.

In the aspect in the test, there's nothing being executed so it's hard to detect. I propose the aspect should perform a verifiable action, e.g. set a boolean flag that can be asserted in the test.

**Review by inkassso — CHANGES_REQUESTED** [review]

**Comment by antoinemeyer** [comment]
> While this change does fix the root cause, I don't think the solution is correct.
> 
> From what I understand, the only difference now is unwrapping the proxy, creating the spy from the actual service instance instead of the proxy, and injecting that spy directly into the target bean. However, that removes the proxy and with it also any intercepting actions, e.g. Transaction handling, Async execution or similar. I believe that should be kept, i.e. when the spied bean is a proxy, don't overwrite the proxy in the target bean, but instead just overwrite the target in the proxy. See [WorkingLoggingServiceTest4_ManualInjectionWithinProxy.java](https://github.com/inkassso/mock-in-bean-issue-23/blob/master/src/test/java/com/github/inkassso/mockinbean/issue23/service/WorkingLoggingServiceTest4_ManualInjectionWithinProxy.java), where I got this working.
> 
> In the aspect in the test, there's nothing being executed so it's hard to detect. I propose the aspect should perform a verifiable action, e.g. set a boolean flag that can be asserted in the test.

Thanks for the feedback.
I changed the code so that the original aspect behavior is now maintained.

**Comment by antoinemeyer** [comment]
> Thanks for the feedback. I changed the code so that the original aspect behavior is now maintained.

@inkassso , any last feedback? If not, I'll move forward with this change.

**Review by inkassso — APPROVED** [review]
Looks perfect now! 💯

**Review by inkassso — APPROVED** [review]

**Review by inkassso — CHANGES_REQUESTED** [review]
Unrelated to the bug, but I have yet another issue that could be fixed in the same release.

I can't put a comment directly on the line, but please see line [BeanUtils.java:78](https://github.com/antoinemeyer/mock-in-bean/pull/28/files#diff-9a3c92fc03baa1ad36c64f3a6ff72ee7731432445fb2f31771915563f5da31f1L76), where the last argument is a lambda deciding whether a bean field matches the type supposed to be spied. It is the `equals` method, i.e. a strict class comparison, which may cause problems under certain circumstances.

Imagine having `ProviderService` as an interface and at least one implementation, e.g. `RestProviderService`. The interface is used in `LoggingService` like now, but the test specifies
```java
@MockInBean(LoggingService.class)
RestProviderService providerService;
```

I tried that out and apparently that's an issue because of this strict comparison. The type to spy declared in the test is not exactly the same class as the type used in the target bean. But it is a subclass thereof, so that condition only needs to be adjusted accordingly:
```java
field -> field.getType().isAssignableFrom(type)
```

Already tested it out locally and it works. However, there are edge cases to be considered, e.g. what if the bean declares two fields, one using the interface and one using the subclass (as dirty as it sounds)? Spring definitely allows two beans with the same supertype in the context, in such case it's customary to mark one bean of a subclass as primary, which will be injected into the field declared with the supertype, while beans of other subclasses will be injected only when declared with their respective subtype.

**Comment by antoinemeyer** [comment]
> Unrelated to the bug, but I have yet another issue that could be fixed in the same release.

@inkassso, I have created https://github.com/antoinemeyer/mock-in-bean/pull/32 to fix that issue. Could you have a look?

**Pull request closed without merging**
